# Generated by Django 4.2.16 on 2026-02-26 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='角色名', max_length=100)),
                ('gender', models.CharField(choices=[('male', '男性'), ('female', '女性'), ('other', '其他'), ('unknown', '未知')], default='unknown', max_length=10)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('appearance', models.TextField(blank=True, help_text='外貌描述')),
                ('backstory', models.TextField(blank=True, help_text='背景故事')),
                ('ruleset_slug', models.CharField(help_text='规则集 slug', max_length=50)),
                ('race_slug', models.CharField(help_text='种族 slug', max_length=50)),
                ('subrace_slug', models.CharField(blank=True, help_text='亚种族 slug', max_length=50)),
                ('class_slug', models.CharField(help_text='职业 slug', max_length=50)),
                ('background_slug', models.CharField(help_text='背景 slug', max_length=50)),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('experience_points', models.PositiveIntegerField(default=0)),
                ('ability_method', models.CharField(choices=[('standard_array', '标准数组'), ('point_buy', '点数购买'), ('manual', '手动输入')], default='standard_array', max_length=20)),
                ('strength', models.PositiveSmallIntegerField(default=10)),
                ('dexterity', models.PositiveSmallIntegerField(default=10)),
                ('constitution', models.PositiveSmallIntegerField(default=10)),
                ('intelligence', models.PositiveSmallIntegerField(default=10)),
                ('wisdom', models.PositiveSmallIntegerField(default=10)),
                ('charisma', models.PositiveSmallIntegerField(default=10)),
                ('skill_proficiencies', models.JSONField(default=list)),
                ('personality_trait', models.TextField(blank=True)),
                ('ideal', models.TextField(blank=True)),
                ('bond', models.TextField(blank=True)),
                ('flaw', models.TextField(blank=True)),
                ('known_spells', models.JSONField(default=list, help_text='已知法术列表')),
                ('prepared_spells', models.JSONField(default=list, help_text='已准备法术列表')),
                ('inventory', models.JSONField(default=list, help_text='物品栏')),
                ('copper', models.PositiveIntegerField(default=0)),
                ('silver', models.PositiveIntegerField(default=0)),
                ('gold', models.PositiveIntegerField(default=0)),
                ('platinum', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False, help_text='是否公开分享')),
                ('share_token', models.UUIDField(default=uuid.uuid4, help_text='分享链接Token', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
