# Generated by Django 4.2.16 on 2026-02-26 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='唯一标识符，如 dnd5e_2014', unique=True)),
                ('name', models.CharField(help_text='显示名称', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='唯一标识符，如 elf')),
                ('name', models.CharField(help_text='中文名', max_length=100)),
                ('name_en', models.CharField(blank=True, help_text='英文名', max_length=100)),
                ('description', models.TextField(blank=True, help_text='种族简介')),
                ('speed', models.PositiveSmallIntegerField(default=30, help_text='移动速度（尺）')),
                ('size', models.CharField(default='中型', help_text='体型', max_length=20)),
                ('ability_bonuses', models.JSONField(default=dict, help_text='属性加值，如 {"dex": 2}')),
                ('traits', models.JSONField(default=list, help_text='种族特性列表')),
                ('languages', models.JSONField(default=list, help_text='掌握语言列表')),
                ('has_subraces', models.BooleanField(default=False, help_text='是否有亚种族')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='races', to='gamedata.ruleset')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('ruleset', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='CharClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='唯一标识符，如 wizard')),
                ('name', models.CharField(help_text='中文名', max_length=100)),
                ('name_en', models.CharField(blank=True, help_text='英文名', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('hit_die', models.PositiveSmallIntegerField(help_text='命中骰面数，如 6/8/10/12')),
                ('primary_ability', models.CharField(help_text='主要属性，如 智力', max_length=50)),
                ('saving_throw_proficiencies', models.JSONField(default=list, help_text='豁免熟练项，如 ["int", "wis"]')),
                ('armor_proficiencies', models.JSONField(default=list, help_text='护甲熟练项')),
                ('weapon_proficiencies', models.JSONField(default=list, help_text='武器熟练项')),
                ('skill_choices_count', models.PositiveSmallIntegerField(default=2, help_text='可选技能数量')),
                ('skill_choices', models.JSONField(default=list, help_text='可选技能列表')),
                ('is_spellcaster', models.BooleanField(default=False, help_text='是否有施法能力')),
                ('spellcasting_ability', models.CharField(blank=True, help_text='施法属性，如 int', max_length=10)),
                ('level_features', models.JSONField(default=dict, help_text='各等级获得的特性')),
                ('starting_equipment', models.JSONField(default=list, help_text='初始装备选项')),
                ('roles', models.JSONField(default=list, help_text='职业定位标签列表')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='gamedata.ruleset')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('ruleset', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Subrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('ability_bonuses', models.JSONField(default=dict, help_text='额外属性加值')),
                ('traits', models.JSONField(default=list, help_text='亚种族特性列表')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subraces', to='gamedata.race')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('race', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(default=dict, help_text='各等级获得的子职业特性')),
                ('char_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subclasses', to='gamedata.charclass')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('char_class', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(help_text='中文名', max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('level', models.PositiveSmallIntegerField(help_text='法术环级，0=戏法')),
                ('school', models.CharField(choices=[('abjuration', '防护'), ('conjuration', '咒法'), ('divination', '预言'), ('enchantment', '惑控'), ('evocation', '塑能'), ('illusion', '幻术'), ('necromancy', '死灵'), ('transmutation', '变化')], max_length=20)),
                ('casting_time', models.CharField(help_text='施法时间，如 1个动作', max_length=50)),
                ('range', models.CharField(help_text='射程', max_length=50)),
                ('components', models.JSONField(default=list, help_text='法术成分，如 ["V", "S", "M"]')),
                ('material', models.CharField(blank=True, help_text='材料成分详情', max_length=200)),
                ('duration', models.CharField(help_text='持续时间', max_length=50)),
                ('concentration', models.BooleanField(default=False, help_text='是否需要专注')),
                ('ritual', models.BooleanField(default=False, help_text='是否可以仪式施法')),
                ('description', models.TextField(help_text='法术描述')),
                ('higher_levels', models.TextField(blank=True, help_text='高环施放效果')),
                ('classes', models.JSONField(default=list, help_text='可使用的职业 slug 列表，如 ["wizard", "sorcerer"]')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spells', to='gamedata.ruleset')),
            ],
            options={
                'ordering': ['level', 'name'],
                'unique_together': {('ruleset', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('skill_proficiencies', models.JSONField(default=list, help_text='技能熟练项，如 ["insight", "religion"]')),
                ('tool_proficiencies', models.JSONField(default=list, help_text='工具熟练项')),
                ('languages_count', models.PositiveSmallIntegerField(default=0, help_text='额外语言数量')),
                ('feature_name', models.CharField(help_text='背景特性名称', max_length=100)),
                ('feature_description', models.TextField(help_text='背景特性描述')),
                ('starting_equipment', models.JSONField(default=list, help_text='初始装备列表')),
                ('starting_gold', models.PositiveSmallIntegerField(default=0, help_text='初始金币（gp）')),
                ('personality_traits', models.JSONField(default=list, help_text='性格特质预设列表（8条）')),
                ('ideals', models.JSONField(default=list, help_text='理念预设列表（6条）')),
                ('bonds', models.JSONField(default=list, help_text='牵绊预设列表（6条）')),
                ('flaws', models.JSONField(default=list, help_text='缺点预设列表（6条）')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backgrounds', to='gamedata.ruleset')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('ruleset', 'slug')},
            },
        ),
    ]
