# Generated by Django 4.2.16 on 2026-03-01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamedata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='唯一标识符')),
                ('name', models.CharField(help_text='中文名', max_length=100)),
                ('name_en', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('weapon', '武器'), ('armor', '护甲'), ('adventuring-gear', '冒险装备'), ('tool', '工具'), ('pack', '套装'), ('vehicle', '载具'), ('mount', '坐骑')], help_text='物品分类', max_length=20)),
                ('cost', models.CharField(blank=True, help_text='价格，如 10 gp', max_length=20)),
                ('weight', models.FloatField(default=0, help_text='重量（磅）')),
                ('damage', models.CharField(blank=True, help_text='伤害，如 1d8', max_length=20)),
                ('damage_type', models.CharField(blank=True, help_text='伤害类型', max_length=20)),
                ('properties', models.JSONField(default=list, help_text='武器属性列表')),
                ('ac', models.PositiveSmallIntegerField(blank=True, help_text='护甲AC', null=True)),
                ('description', models.TextField(blank=True, help_text='物品描述')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gamedata.ruleset')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('ruleset', 'slug')},
            },
        ),
    ]
