# Generated by Django 4.2.16 on 2026-03-04 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bot_id', models.CharField(max_length=20, unique=True, verbose_name='机器人QQ号')),
                ('nickname', models.CharField(max_length=100, verbose_name='昵称')),
                ('master_qq', models.CharField(max_length=20, verbose_name='主人QQ号')),
                ('version', models.CharField(blank=True, default='', max_length=50, verbose_name='版本')),
                ('api_key', models.CharField(max_length=64, unique=True, verbose_name='API Key')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('is_public', models.BooleanField(default=True, verbose_name='公开显示')),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '离线'), ('unknown', '未知')], default='unknown', max_length=10, verbose_name='在线状态')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='最后在线')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bots', to=settings.AUTH_USER_MODEL, verbose_name='主人')),
            ],
            options={
                'verbose_name': '机器人',
                'verbose_name_plural': '机器人',
                'ordering': ['-created_at'],
            },
        ),
    ]
